#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# Fish
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update

sudo apt install -y neovim alacritty gh libasound2-dev libudev-dev

# Fish
chsh -s /usr/bin/fish

if ! [ -x "$(command -v rustup)" ]
then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	rustup component add rust-analyzer
fi

cat dconf-settings.ini | dconf load /
